name: DVC Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: "* 1 * * *"

jobs:
  dvc_operations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.5"

      - name: Install DVC
        run: |
          pip install dvc
          pip install dvc[gdrive]

      - name: Configure DVC remote
        run: |
          dvc remote modify storage gdrive_acknowledge_abuse true
          dvc remote modify storage url gdrive://1CUWjhnRnxFJQe1eN8FCLoyHXE4Fvd5rD
          dvc remote default storage

      - name: Pull data from DVC remote
        run: |
          dvc pull
